# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_auto_20160606_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default=False, max_length=128, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default=False, max_length=128, verbose_name='\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
