# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0003_auto_20160606_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7528\u6237\u8868', 'verbose_name_plural': '\u7528\u6237\u8868'},
        ),
    ]
