# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0004_auto_20160606_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=128)),
                ('System', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=64)),
                ('Port', models.IntegerField(default=22)),
                ('IpAddress', models.GenericIPAddressField(unique=True)),
                ('NetMask', models.GenericIPAddressField()),
                ('Status', models.CharField(choices=[('up', 'UP'), ('down', 'Down')], default='up', max_length=64)),
                ('Memo', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=64)),
                ('PassWord', models.CharField(blank=True, max_length=256, null=True)),
                ('AuthType', models.CharField(choices=[('key_rsa', 'KEY/RSA'), ('password', 'PASSWORD')], default='password', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthorized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostGroup', models.ManyToManyField(to='Control.HostGroup')),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='Idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control.IDC'),
        ),
    ]
